In [1]:
import numpy as np
x = np.array([[1, 2, 3] , [4, 5, 6]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


In [2]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
x.shape

(2, 3)

In [4]:
x.dtype

dtype('int64')

In [5]:
x[0,1]

np.int64(2)

In [6]:
x[0]

array([1, 2, 3])

In [7]:
x[1]

array([4, 5, 6])

In [8]:
x[1,2]

np.int64(6)

In [9]:
zeros = np.zeros((2,3))

**create a numpy array consisting only zeros**

In [10]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
zeros.dtype

dtype('float64')

In [12]:
zeros = np.zeros((2,3) , dtype='int64')

In [13]:
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
zeros.dtype

dtype('int64')

In [15]:
rng = np.arange(15)

**create numpy arr of 15 elements starting from 0**

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
lspace = np.linspace(1,10,20)

**creates numpy arr; linspace(a,b,c) generates c number of elements between [a , b] and each element is equally spaced**

In [18]:
lspace

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [19]:
lspace = np.linspace(1,10,19)

In [20]:
lspace

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [21]:
emp = np.empty((2,3))

**creates a 2x3 2d-np_array with random numbers**

In [22]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.86919378e-306, 1.89146896e-307, 7.56571288e-307]])

In [23]:
emp = np.empty((2,3) , dtype='int32')

In [24]:
emp

array([[    101,     109,     112],
       [      0,       0, 4456560]], dtype=int32)

In [25]:
emp_like = np.empty_like(x)

**creates an np arr with random elements but with shape like arr x**

In [26]:
emp_like

array([[25895968444448860, 23925768161198147, 32370111954616435],
       [32932988893462620, 18296268629999715, 27303364806049904]])

In [27]:
i = np.identity(10)

**creates a 10x10 identity matrix**

In [28]:
i

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [29]:
i = np.identity(10 , dtype='int8')

In [30]:
i

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [31]:
arr = np.arange(30)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

**arr is a 1d array here and next we reshape it**

In [33]:
arr.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [34]:
arr = np.arange(1,31)

In [35]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [36]:
arr.reshape(3,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [37]:
arr.reshape(10,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [38]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [39]:
arr = arr.reshape(6,5)

In [40]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [41]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

**converted a 2d arr to a 1d arr (the reverse of reshape)**

In [42]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [43]:
arr = arr.ravel()

In [44]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [45]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [47]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**finding sum of column elements**

In [48]:
x.sum(axis=0)

array([12, 15, 18])

**finding sum of row elements**

In [49]:
x.sum(axis=1)

array([ 6, 15, 24])

In [50]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Transpose of matrix(2d-array)**

In [51]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [52]:
for item in x:
    print(item)

[1 2 3]
[4 5 6]
[7 8 9]


In [53]:
for item in x.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [54]:
x.ndim

2

In [55]:
x.size

9

**find total bytes cosumed by x : nbytes**

In [56]:
x.nbytes 

72

In [57]:
a = np.array([1,4,5,2,3])

**find the position where the largest element is present : argmax() , smallest element : argmin()**

In [58]:
a.argmax()   

np.int64(2)

In [59]:
a.argmin()

np.int64(0)

**argsort() : gives an array with the positions of elements arranged in ascending order**

In [60]:
a.argsort()

array([0, 3, 4, 1, 2])

*arg always gives the position and not the value of the element*

In [61]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
x.argmax()

np.int64(8)

In [63]:
x.argmin()

np.int64(0)

**treats x as a 1d array [1,2,3,4,5,6,7,8,9] and gives the position of the largest or smallest element**

In [64]:
x.argmax(axis=0)

array([2, 2, 2])

In [65]:
x.argmin(axis=1)

array([0, 0, 0])

In [66]:
x.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [67]:
x.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [68]:
x.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [69]:
x.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
x.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [71]:
y = np.array([[4,7,2],[5,9,1],[6,5,0]])

In [72]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
y

array([[4, 7, 2],
       [5, 9, 1],
       [6, 5, 0]])

**adding two matrices position-wise**

In [74]:
x + y

array([[ 5,  9,  5],
       [ 9, 14,  7],
       [13, 13,  9]])

**multiplying two matrices position-wise**

In [75]:
x * y

array([[ 4, 14,  6],
       [20, 45,  6],
       [42, 40,  0]])

**square-root of each element**

In [76]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [77]:
y

array([[4, 7, 2],
       [5, 9, 1],
       [6, 5, 0]])

In [78]:
y.sum()

np.int64(39)

In [79]:
y.max()

np.int64(9)

In [80]:
y.min()

np.int64(0)

In [81]:
y

array([[4, 7, 2],
       [5, 9, 1],
       [6, 5, 0]])

In [82]:
np.where(y==5)

(array([1, 2]), array([0, 1]))

In [83]:
np.where(y>5)

(array([0, 1, 2]), array([1, 1, 0]))

In [84]:
np.count_nonzero(y)

np.int64(8)

In [85]:
np.nonzero(y)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))