In [1]:
from scipy import sparse

In [2]:
import numpy as np

In [3]:
x = np.identity(4 , dtype = "int8")

In [4]:
x

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [5]:
sparse_matrix = sparse.csr_matrix(x)

In [6]:
sparse_matrix

<Compressed Sparse Row sparse matrix of dtype 'int8'
	with 4 stored elements and shape (4, 4)>

In [7]:
format(sparse_matrix)

"<Compressed Sparse Row sparse matrix of dtype 'int8'\n\twith 4 stored elements and shape (4, 4)>\n  Coords\tValues\n  (0, 0)\t1\n  (1, 1)\t1\n  (2, 2)\t1\n  (3, 3)\t1"

In [8]:
print(format(sparse_matrix))

<Compressed Sparse Row sparse matrix of dtype 'int8'
	with 4 stored elements and shape (4, 4)>
  Coords	Values
  (0, 0)	1
  (1, 1)	1
  (2, 2)	1
  (3, 3)	1


sparse_matrix only stores the non zero values of a matrix. x is an identity matrix and it is converted to sparse matrix and only the 1's are stored with their index.
Now converrsely using the same idea, a matrix can be created where we store some values from a dataset(array) into specific positions of a matrix and rest of the positions will automatically be filled to be zero

In [9]:
data = [1,2,3,4]
row = [0,1,0,2]   #row positions
column = [0,2,2,1]  #column postions
csr = sparse.csr_matrix((data , (row,column)) , shape = (3,3))
print(csr)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (3, 3)>
  Coords	Values
  (0, 0)	1
  (0, 2)	3
  (1, 2)	2
  (2, 1)	4


In [10]:
#convert to csr to array
print(csr.toarray())

[[1 0 3]
 [0 0 2]
 [0 4 0]]


In [11]:
#printing the non zero values of a matrix OR, printing the values of the csr matrix after conversion
print(csr.data)
print("\n")
print(sparse_matrix.data)

[1 3 2 4]


[1 1 1 1]
